name: hummingboard-kernel
version: 4.1rc
summary: Kernel
description: Includes support for humming board.
type: kernel
confinement: strict
grade: stable

parts:
  kernel:
    plugin: kernel-madper
    source: https://github.com/madper/linux-apparmor-backports.git
    source-type: git
    source-branch: hb-4.1-aa3.6
    kdefconfig: [imx_v6_v7_defconfig]
    kconfigs:
      - CONFIG_LOCALVERSION="-lite"
      - CONFIG_SQUASHFS=y
      - CONFIG_SQUASHFS_XZ=y
      - CONFIG_SND_SOC_IMX_SGTL5000=n
      - CONFIG_SECURITY_APPARMOR=y
      - CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
      - CONFIG_SECURITY_APPARMOR_UNCONFINED_INIT=y
      - CONFIG_SECURITY_APPARMOR_HASH=y
      - CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y
      - CONFIG_DEFAULT_SECURITY_APPARMOR=y
      - CONFIG_DEFAULT_SECURITY="apparmor"
      - CONFIG_SECURITY=y
      - CONFIG_SECURITYFS=y
      - CONFIG_SECURITY_NETWORK=y
      - CONFIG_SECURITY_PATH=y
      - CONFIG_TTY=y
      - CONFIG_UNIX98_PTYS=y
      - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
      - CONFIG_SECCOMP=y
      - CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
      - CONFIG_SECCOMP_FILTER=y
    kernel-image-target: zImage
    kernel-device-trees:
      - imx6q-hummingboard
    build-packages: [bc, kmod, cpio, lzop, u-boot-tools]
